@baseUrl = http://localhost:5000

POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "demoUser1",
  "email": "demo1@email.com",
  "password": "mypassword"
}

###

# @name login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "demo@email.com",
    "password": "mypassword"
}

###

@token = {{login.response.body.token}}
GET http://localhost:5000/api/profile/me
Authorization: Bearer {{token}}